src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Latest_Sales_Dealer__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Latest Sales Dealer for this contact 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_LatestSalesDealer&quot;</description>
        <label>Latest Sales Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Latest Sales Dealers (Account))</relationshipLabel>
        <relationshipName>Sales_Dealers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Dealer__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Main Aftersales Dealer for this contact 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_MainDealer&quot;</description>
        <label>Main Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Main Dealer)</relationshipLabel>
        <relationshipName>Main_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Aftersales__c.object
<CustomObject>
    <description>Contact Portfolio: To record MBCL Aftersales record
Changed object name from &quot;Aftersales Record&quot; to &quot;Aftersales&quot;</description>
    <fields>
        <fullName>Service_Contact__c</fullName>
        <description>Who brings the vehicle to service
Attribute in Data Dictionary object Aftersales is &quot;Service_Contact&quot;</description>
        <label>Service_Contact</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Aftersales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Dealer__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Aftersales Record 
Function: Code of the dealer that deliver the service
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Aftersales is &quot;Service_Dealer&quot;</description>
        <inlineHelpText>Code of the dealer that deliver the service</inlineHelpText>
        <label>Service Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Aftersales_Record</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aftersales</label>
    <nameField>
        <label>Service No*</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aftersales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales__c.object
<CustomObject>
    <description>Contact Porfolio: To record Sales record linked to each customer</description>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <description>/* 
Created by: Tony Li
Used by: Tony Li 
Function: Retail Contact linked to the sales record 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Sales is &quot;Sales_Contact&quot;</description>
        <label>Sales Contact</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Record</relationshipLabel>
        <relationshipName>Sales_Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Dealer__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Sales 
Function: Sales dealer code in CRM 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Sales is &quot;Sales_Dealer&quot;</description>
        <inlineHelpText>Sales dealer code in CRM</inlineHelpText>
        <label>Sales Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Record</relationshipLabel>
        <relationshipName>Dealer_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Sales 
Function: The sales person involved in the contract
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Sales is &quot;Sales_Person&quot;</description>
        <inlineHelpText>The sales person involved in the contract</inlineHelpText>
        <label>Sales Person</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Vehicle_ID__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle linked to the sale in the system 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Sales is &quot;Sales_VehicleID&quot;</description>
        <label>Sales Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Sales</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales</label>
    <nameField>
        <label>Sales Order No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>Latest_Sales_Person__c</fullName>
        <description>Attribute in Data Dictionary object Vehicle is ”Vehicle_LatestSalesPerson“</description>
        <label>Latest Sales Person</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is&quot;VehicleRel_VehicleID&quot;</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UtilSales.cls
/*
    Type:       Utility for TriggerSales and TriggerAftersales
    Purpose:    If Sales/Aftersales has change, just update Account, 
                Vehicle and Vehicle Relationship corresponding fields 
                according to related Sales/Aftersales.
    User Story: US-CP-014, US-CP-12
    Used By:    TriggerSales, TriggerAftersales
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-05
    2. Mouse Stop populating "Latest Handover Date", "Latest Contract Date" 
       and "Latest Invoice Date" on related vehicle record on 2013-03-19
*/
public class UtilSales {
    private static void updateSobjects(List<Sobject> sos) {
        try {
            update sos;
        }
        catch (DMLException e) {
            trigger.new[0].addError(e.getDMLMessage(0));
            System.debug('UtiSales DMLException Exception: ' + e);
        }
    }
    
    // Update the corresponding Vehicle by valid sales
    public static void updateVehicle(List<Sales__c> validSales) {
        List<Vehicle__c> vehicles = new List<Vehicle__c>();
        for (Sales__c sale : validSales) {
            Vehicle__c vehicle = new Vehicle__c(
                Id = sale.Sales_Vehicle_ID__c,
                Latest_Sales_Person__c = sale.Sales_Person__c
            );
            vehicles.add(vehicle);
        }
        
        updateSobjects(vehicles);
    }
    
    // Update all related Vehicle Relationship records by the valid Sales/valid Aftersales
    public static void updateVehicleRelationship(Map<Id, Sobject> vehicleIdSOMap, 
                                                 Map<String, String> fieldMappingMap) {
        List<Vehicle_Relationship__c> relationships = 
            new List<Vehicle_Relationship__c>();
        // If more relationship fields need to update, we just need to 
        // change the mapping constant in constant class 
        for (Vehicle__c vehicle : [SELECT Id, (SELECT Id FROM Vehicle_Relationships__r)
                                   FROM Vehicle__c
                                   WHERE Id IN :vehicleIdSOMap.keySet()]) {
            // Get the valid Sales by vehicle Id
            Sobject so = vehicleIdSOMap.get(vehicle.Id);
            
            // Update all related Vehicle Relationship records by the valid Sales
            for (Vehicle_Relationship__c relationship : vehicle.Vehicle_Relationships__r) {
                for (String vehicleRelationshipField : fieldMappingMap.keySet()) {
                    // Populate the vehicle relationship field value with 
                    // corresponding Sales/Aftersales field value
                    relationship.put(vehicleRelationshipField, 
                        so.get(fieldMappingMap.get(vehicleRelationshipField)));
                }
                
                relationships.add(relationship);
            }
            
            updateSobjects(relationships);
        }
    }
    
    // If this method is invoked in Sales Trigger, fix = 'Sales'
    // If this method is invoked in Aftersales trigger, fix = 'Service'
    public static void updateAccount(Map<Id, Sobject> accIdSOMap, String fix) {
        List<Account> accs = new List<Account>();
        for (Account acc : [SELECT Id, Latest_Sales_Dealer__c, Main_Dealer__c,
                                   (SELECT Sales_Dealer__c 
                                    FROM Sales_Person_Account__r),
                                   (SELECT Service_Dealer__c 
                                    FROM Aftersales__r)
                            FROM Account
                            WHERE Id IN :accIdSOMap.keySet()]) {
            // Update Latest Sales Dealer by Sales or Aftersales
            acc.put('Latest_' + fix + '_Dealer__c', 
                accIdSOMap.get(acc.Id).get(fix + '_Dealer__c'));
            
            // Count all valid "Sales" and "Aftersales" record related to this account, 
            //   and update the Account "Main Dealer" with the main used dealer.
            acc.Main_Dealer__c = getMainDealer(acc.Sales_Person_Account__r, 
                                               acc.Aftersales__r);
            accs.add(acc);
        }
        
        updateSobjects(accs);
    }
    
    public static Id getMainDealer(List<Sales__c> sales, 
                                   List<Aftersales__c> aftersales) {
        List<Id> dealerIds = new List<Id>();
        // Add sales dealer into accIds list
        for (Sales__c sale : sales) {
            dealerIds.add(sale.Sales_Dealer__c);
        }
        
        // Add service dealer into accs list
        for (Aftersales__c aftersale : aftersales) {
            dealerIds.add(aftersale.Service_Dealer__c);
        }
        
        // Populate the map with dealerId and corresponding frequency
        Map<Id, Integer> dealerIdFrequencyMap = new Map<Id, Integer>();
        for (Id dealerId : dealerIds) {
            Integer count = dealerIdFrequencyMap.get(dealerId);
            dealerIdFrequencyMap.put(dealerId, count == null ? 1 : ++count);
        }
        System.debug('dealerIdFrequencyMap=>' + dealerIdFrequencyMap);
        
        // Get the mainDealerId by comparing their frequency
        Id mainDealerId = null;
        for (Id dealerId : dealerIdFrequencyMap.keySet()) {       
            if (mainDealerId == null) {
                mainDealerId = dealerId;
            }
            else {
                if (dealerIdFrequencyMap.get(mainDealerId) < 
                        dealerIdFrequencyMap.get(dealerId)) {
                    mainDealerId = dealerId;
                }
            }
        }
        
        return mainDealerId;
    }
}