src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <label>Dealer City</label>
        <referenceTo>Dealer_City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
        <picklist>
            <picklistValues>
                <fullName>Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zhejiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tianjin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tibet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xinjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sichuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yunnan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chongqing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangdong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guizhou</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Participating_Region_Province__c</fullName>
        <label>Participating Region-Province</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E	Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E	Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E	Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E	Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E Zhejiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Tianjin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Tibet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Xinjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N	Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S	Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S	Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S	Sichuan</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/objects/Campaign_City__c.object
<CustomObject>
    <description>Campaign:</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Cities</relationshipLabel>
        <relationshipName>Campaign_Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <label>Dealer City</label>
        <referenceTo>Dealer_City__c</referenceTo>
        <relationshipLabel>Campaign Cities</relationshipLabel>
        <relationshipName>Campaign_Cities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Campaign City</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Package__c.object
<CustomObject>
    <description>Campaign: Combination of campaign offerings</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Packages</relationshipLabel>
        <relationshipName>Campaign_Packages_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dealer_City__c.object
<CustomObject>
    <description>Campaign:</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tianjin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zhejiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangdong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guizhou</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hainan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chongqing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sichuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tibet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xinjiang</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dealer City</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Cities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <formula>Dealer__r.Dealer_City__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participating Campaigns</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CampaignPlanningController.cls
/*
    Type:       controller
    Purpose:    Campaign Planning General Controller
    User Story: US-Cpn-002 - Select participating region/province/city for a central marketing campaign

    Used By:    VF Page - CampaignPlanning.Page
    ---------------------------------------------------------------
    History:

    05-Mar-2013 Jorry Chen (Breakingpoint)    Created
    22-Mar-2013 Jorry Chen (Breakingpoint)    Update: 
                                delete "MB_Sub_Region__c", "Smart_Sub_Region__c", "Sub_Region__c" from query fields
*/

public class CampaignPlanningController {
        /* Public Properties */
        public Campaign myCampaign {get;set;}   
        public List<clsDealerCity> DealerCityList {get;set;}
        public List<clsDealer> partiDealerList {get; set;}
         
        /* Static Variables */
        
        /* Private Properties */
        private Map<String, Set<String>> regionMap;
        private Set<String> ProvinceSet;
        private List<Dealer_City__c> CityList;
        
        private List<Campaign_City__c> campaignCityList;
        private List<Campaign_City__c> campaignCityDelList;
        private List<Campaign_City__c> campaignCityInsList;
        
        private List<Participating_Dealer__c> pDealerList;
        private List<Participating_Dealer__c> pDealerListDel;
        private List<Participating_Dealer__c> pDealerListIns;
        
        private set<ID> cityIdListIn;
        private set<ID> cityIdListOut;
        private set<ID> cityIdListAll;
        
        /* Constructors */
        
        /* Public Methods */
        public PageReference queryDealers() {
                try {
                        fnQueryDealers();
                        return null;
                } catch(exception ex) {
                        return null;
                }
        }
        
        public PageReference selectRegion() {
                try {
                        fuQueryCities();
                        fnQueryDealers();
                        return null;
                } catch (exception ex) {
                        return null;
                }
        }
        
        public PageReference cancel() {
                return null;
        }
        
        // the class will remove the unchecked cities and insert new one.
        public PageReference Save() {           
                SaveCampaignCity();
                SaveParticentDealers();
                return null;
        }
        
        /* Private Methods */
        private void fuQueryCities() {
                try {
                        DealerCityList.clear(); 
                        if(myCampaign.Participating_Region_Province__c <> null && myCampaign.Participating_Region_Province__c <> '') 
                                CityList = Database.query(generateQueryString(myCampaign.Participating_Region_Province__c));
                        else 
                                return;
                                
                        //find the existed dealer cities in the select region
                        for(Integer i = 0; i < cityList.size(); i++) {
                                Boolean blExist = false;
                                for(Campaign_City__c cpCity : campaignCityList) {                               
                                        if(cpCity.Dealer_City__c == cityList[i].Id) {
                                                blExist = true;
                                                break;
                                        }
                                }
                                if(blExist) DealerCityList.add(new clsDealerCity(cityList[i], true));
                                else DealerCityList.add(new clsDealerCity(cityList[i],false));
                        }
                
                        return;
                } catch (exception ex) {
                        return;
                }               
        }
        
        
        private void fnQueryDealers() {
                try {                   
                        cityIdListIn = new Set<ID>();
                        cityIdListOut = new Set<ID>();
                        cityIdListAll = new Set<ID>();
                        
                        for(clsDealerCity city : DealerCityList) {
                                if(city.isChecked) {
                                        cityIdListIn.add(city.dealerCity.Id);
                                }       
                        }
                        
                        partiDealerList = queryDealerList(myCampaign.Id, cityIdListAll, cityIdListIn, cityIdListOut);
                        
                        return;
                } catch (exception ex) {
                        return;         
                }
        }
        
        private void SaveParticentDealers() {
                Savepoint sp = Database.setSavepoint();
                try {
                        List<Account> pDealercheckedList = new List<Account>();
                        pDealerListIns = new List<Participating_Dealer__c>();
                        
                        for(clsDealer pdealer : partiDealerList) {
                                if(pdealer.isChecked) {
                                        pDealercheckedList.add(pdealer.dealer);
                                }
                        }
                        
                        for(Integer i = 0; i < pDealercheckedList.size(); i++) {
                                Boolean blExist = false;
                                for(Integer j = 0; j < pDealerList.size(); j++) {
                                        if(pDealercheckedList[i].Id == pDealerList[j].Dealer__c) {
                                                pDealerList.remove(j);
                                                blExist = true;
                                                break;
                                        }
                                }
                                if(!blExist) {
                                        pDealerListIns.add(new Participating_Dealer__c(Dealer__c = pDealercheckedList[i].Id, Campaign__c = myCampaign.Id));                                     
                                }
                        }
                        
                        if(pDealerListIns.size() > 0) {
                                insert pDealerListIns;
                        }
                        
                        if(pDealerList.size() > 0) {
                                delete pDealerList;
                        }                       
                } catch (exception ex) {
                        Database.rollback(sp);
                        return;
                }
        }
        
        private void SaveCampaignCity() {
                Savepoint sp = Database.setSavepoint();
                try {
                        List<Dealer_City__c> dCitycheckedList = new List<Dealer_City__c>();
                        campaignCityInsList = new List<Campaign_City__c>();
                        
                        for(clsDealerCity cpCity : DealerCityList) {
                                if(cpCity.isChecked) {
                                        dCitycheckedList.add(cpCity.dealerCity);
                                }
                        }
                        
                        for(Integer i = 0; i < dCitycheckedList.size(); i++) {
                                Boolean blExist = false;
                                for(Integer j = 0; j < campaignCityList.size(); j++) {
                                        if(campaignCityList[j].Dealer_City__c == dCitycheckedList[i].Id) {
                                                blExist = true;
                                                campaignCityList.remove(j);
                                        }
                                }
                                if(!blExist) {
                                        campaignCityInsList.add(new Campaign_City__c(Campaign__c = myCampaign.Id, Dealer_City__c = dCitycheckedList[i].Id));
                                }
                        }
                        
                        if(campaignCityList.size() > 0) {
                                delete campaignCityList;
                        }
                        
                        if(campaignCityInsList.size() > 0) {
                                insert campaignCityInsList;
                        }
                        
                        update new Campaign(id=myCampaign.id, Participating_Region_Province__c=myCampaign.Participating_Region_Province__c);
                        
                        return;
                } catch(exception ex) {
                        Database.rollback(sp);
                        return;
                }               
        }
        
        // get all dealer account in the selected city list
        private List<clsDealer> queryDealerList(Id cpid, set<ID> allIds, set<ID> inIds, set<ID> outIds) {
                try {
                        partiDealerList = new List<clsDealer>();
                        Set<ID> idList = new Set<ID>();
                                        
                        List<Account> dealerList = [select Id, name, Dealer_City__c, Province__c, Dealer_Region__c, Dealer_City_EN__c 
                                                                                from Account 
                                                                                where Dealer_City__c in :inIds
                                                                                order by Dealer_Region__c];
                        
                        for(Participating_Dealer__c pDealer : pDealerList) {
                                idList.add(pDealer.Dealer__c);
                        }
                        
                        for(Account ac : dealerList) {
                                if(idList.contains(ac.Id)) {
                                        partiDealerList.add(new clsDealer(ac, true));
                                } else {
                                        partiDealerList.add(new clsDealer(ac, false));
                                }
                        }
                        
                        return partiDealerList;
                } catch(exception ex) {
                        return null;
                }
        }
        
        private String generateQueryString(String str) {
                try{
                        str = str.replaceAll('\t', ' ');                                        // add to make data qualified.
                        String queryStr = 'Select Id, Name, Province__c, Region__c from Dealer_City__c ';
                        Set<String> regionString = new Set<String>();
                        for(String myStr : str.split(';')){
                                regionString.add(myStr);
                        }
                        
                        if(regionString.contains('All')){
                                return queryStr;
                        }
                                        
                        regionMap = new Map<String, Set<String>>();
                        List<String> regionList = new List<String>();
                        
                        for(String myStr : regionString) {                              
                                if(!regionMap.containsKey(myStr.split(' ')[0])) { 
                                        regionMap.put(myStr.split(' ')[0], new Set<String>());
                                        regionList.add(myStr.split(' ')[0]);
                                }
                                // to handle the picklist values, with more than 2 blank space
                                regionMap.get(myStr.split(' ')[0]).add((myStr.split(' ').size() > 2 ? (myStr.split(' ')[1] + ' ' + myStr.split(' ')[2]) : (myStr.split(' ')[1])));
                        }
                        
                        for(integer i = 0; i < regionList.size(); i++) {
                                if(0 == i) queryStr += 'where (';
                                if(regionMap.get(regionList[i]).contains('All')) {
                                        queryStr += 'Region__c =\'' + regionList[i] + '\') ';
                                } else {
                                        ProvinceSet = regionMap.get(regionList[i]);
                                        queryStr += 'Region__c =\'' + regionList[i] + '\' and Province__c in :ProvinceSet) ';
                                }
                                if(regionList.size()-1 <> i) queryStr += 'or (';
                        }
                        
                        return queryStr;
                } catch (exception ex){
                        return '';
                }
        }
        /* Inner classes and methods*/
        public class clsDealerCity{
                public Boolean isChecked {get;set;}
                public Dealer_City__c dealerCity {get; set;}
                
                public clsDealerCity(Dealer_City__c city, Boolean isExist) {
                        this.isChecked = isExist;
                        this.dealerCity = city;
                }
        }
        
        public class clsDealer{
                public Boolean isChecked {get;set;}
                public Account dealer {get; set;}
                
                public clsDealer(Account pDealer, Boolean isExist) {
                        this.isChecked = isExist;
                        this.dealer = pDealer;
                }
        }
        
        
        /* Static initialisers */
        public CampaignPlanningController() {           
                Id campaignId = ApexPages.currentPage().getParameters().get('id');
                
                myCampaign = [select id, Participating_Region_Province__c from Campaign where id = :campaignId];
                campaignCityList = [select id, Dealer_City__c from Campaign_City__c where Campaign__c = :campaignId];
                
                //get all default dealer_cities         
                if(myCampaign.Participating_Region_Province__c <> null && myCampaign.Participating_Region_Province__c <> '') 
                        CityList = Database.query(generateQueryString(myCampaign.Participating_Region_Province__c));
                else 
                        CityList = new List<Dealer_City__c>();
                
                //get all campaign_dealers from the campaign record
                pDealerList = [Select id, Name, Campaign__c, Campaign_Package__c, Dealer__c, 
                                        Session_End_Date__c, Session_Start_Date__c
                                from Participating_Dealer__c
                                where Campaign__c = :campaignId];
                
                DealerCityList = new List<clsDealerCity>();               
                cityIdListAll = new set<ID>();
                cityIdListIn = new set<ID>();
                cityIdListOut = new set<ID>();
                
                //find the existed dealer cities
                for(Integer i = 0; i < cityList.size(); i++) {
                        Boolean blExist = false;
                        for(Campaign_City__c cpCity : campaignCityList) {                               
                                if(cpCity.Dealer_City__c == cityList[i].Id) {
                                        blExist = true;
                                        break;
                                }
                        }
                        if(blExist) { 
                                DealerCityList.add(new clsDealerCity(cityList[i], true));
                                cityIdListIn.add(cityList[i].Id);
                                cityIdListAll.add(cityList[i].Id);
                        }
                        else {
                                DealerCityList.add(new clsDealerCity(cityList[i],false));
                                cityIdListOut.add(cityList[i].Id);
                                cityIdListAll.add(cityList[i].Id);
                        }
                }
                
                partiDealerList = queryDealerList(campaignId, cityIdListAll, cityIdListIn, cityIdListOut);
        }

}