src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <label>Dealer City</label>
        <referenceTo>Dealer_City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Campaign_City__c.object
<CustomObject>
    <description>Campaign:</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Cities</relationshipLabel>
        <relationshipName>Campaign_Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <label>Dealer City</label>
        <referenceTo>Dealer_City__c</referenceTo>
        <relationshipLabel>Campaign Cities</relationshipLabel>
        <relationshipName>Campaign_Cities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Campaign City</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Dealer__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer in regards of complaint 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Case Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Dealer)</relationshipLabel>
        <relationshipName>Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Dealer_City__c.object
<CustomObject>
    <description>Campaign:</description>
    <label>Dealer City</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Cities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <formula>Dealer__r.Dealer_City__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participating Campaigns</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UtilCampaignCity.cls
/*
    Type:       Apex Class
    Purpose:    Define methods used in triggerCampaignCity
    User Story: US-Cpn-002, US-Cpn-004
    Used By:    TriggerCampaignCity.trigger
    ---------------------------------------------------------------
    History:
    
	08-Mar-2013 Jorry Chen (Breakingpoint)    Created
*/

public class UtilCampaignCity {
	public static void deleteParticipatingDealer(List<Campaign_City__c> cpCityList){
		Savepoint sp = Database.setSavepoint();
		try{
			List<ID> cityIdList = new List<ID>();
			
			System.debug('@!!!!! begin');
			for(Campaign_City__c city : cpCityList){
				cityIdList.add(city.Dealer_City__c);
				System.debug('@!!!!! city.Dealer_City__c ' + city.Dealer_City__c);
			} 	
			
			List<Participating_Dealer__c> pDealerList = [select id from Participating_Dealer__c
															where Dealer__r.Dealer_City__c in :cityIdList and Campaign__c = :cpCityList[0].Campaign__c];
			
			System.debug('@!!!!! city.Dealer_City__c ' + pDealerList.size());
															
			if(pDealerList.size() > 0) {
				delete pDealerList;
			}
		} catch(exception ex) {
			Database.rollback(sp);
            System.debug('deleteCampaigndealer failed : ' + ex);
		}
	}	
}