src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
        <picklist>
            <controllingField>Province__c</controllingField>
            <picklistValues>
                <fullName>安庆市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>蚌埠市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>亳州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>巢湖市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>池州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>滁州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>阜阳市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>合肥市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>淮北市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>淮南市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>黄山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>六安市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>马鞍山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宿州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>铜陵市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>芜湖市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宣城市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>昆山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>澳门特区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>福州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>金门县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>连江县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>龙岩市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>南平市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宁德市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>莆田市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>泉州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>三明市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>厦门市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>漳州市</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <label>Dealer City</label>
        <referenceTo>Dealer_City__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
        <picklist>
            <picklistValues>
                <fullName>Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zhejiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tianjin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tibet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xinjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sichuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yunnan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chongqing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangdong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guizhou</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Dealer_City__c.object
<CustomObject>
    <description>Campaign:</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tianjin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zhejiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangdong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guizhou</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hainan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chongqing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sichuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tibet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xinjiang</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dealer City</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Cities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UtilAccount.cls
/*
    Type:       Utility for TriggerAccount
    Purpose:    Link Dealer to Dealer City by City CN and Province 
    User Story: US-DS-001
    Used By:    TriggerAccount.trigger
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-28
*/
public class UtilAccount {
    public static void linkDealerCity(List<Account> triggerNew, Id dealerRecordTypeId) {
        if (trigger.isUpdate && trigger.isBefore && trigger.isExecuting) {
            // Get cities, provinces and the dealer 
            // which city or province has change
            Set<Id> dealerIdSet = new Set<Id>();
            Set<String> cities = new Set<String>();
            Set<String> provinces = new Set<String>();

            for (Account acc : triggerNew) {
                // Get the dealer which City CN or Province has change
                Account oldAcc = (Account) trigger.oldMap.get(acc.Id);
                if (acc.RecordTypeId == dealerRecordTypeId && 
                        (acc.City_CN__c != oldAcc.City_CN__c ||
                         acc.Province__c != oldAcc.Province__c)) {
                    dealerIdSet.add(acc.Id);

                    // Populate cities and provinces
                    if (acc.City_CN__c != null) {
                        cities.add(acc.City_CN__c);
                    }

                    if (acc.Province__c != null) {
                        provinces.add(acc.Province__c);
                    }
                }
            }

            // Dealer City Name + Province => Dealer City Id
            Map<String, Id> cityProvince2DealerCityId = 
                new Map<String, Id>();
            for (Dealer_City__c dealerCity : [SELECT Id, Name, Province__c 
                                              FROM Dealer_City__c
                                              WHERE Name IN :cities
                                              AND Province__c IN :provinces]) {
                cityProvince2DealerCityId.put(
                    dealerCity.Name + dealerCity.Province__c, dealerCity.Id);
            }
            System.debug(cityProvince2DealerCityId);

            // Populate dealerCityId by cityProvince2DealerCityId
            for (Account dealer : triggerNew) {
                if (dealerIdSet.contains(dealer.Id)) {
                    dealer.Dealer_City__c = cityProvince2DealerCityId.get(
                        dealer.City_CN__c + dealer.Province__c);
                }
            }
        }
    }
}