src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Latest_Service_Dealer__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Latest Aftersales Dealer for this contact 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_LatestAftersalesDealer&quot;</description>
        <label>Latest Service Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Latest Service Dealers (Account))</relationshipLabel>
        <relationshipName>Service_Dealers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Dealer__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Main Aftersales Dealer for this contact 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_MainDealer&quot;</description>
        <label>Main Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Main Dealer)</relationshipLabel>
        <relationshipName>Main_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Aftersales__c.object
<CustomObject>
    <description>Contact Portfolio: To record MBCL Aftersales record
Changed object name from &quot;Aftersales Record&quot; to &quot;Aftersales&quot;</description>
    <fields>
        <fullName>Service_Contact__c</fullName>
        <description>Who brings the vehicle to service
Attribute in Data Dictionary object Aftersales is &quot;Service_Contact&quot;</description>
        <label>Service_Contact</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Aftersales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Dealer__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Aftersales Record 
Function: Code of the dealer that deliver the service
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Aftersales is &quot;Service_Dealer&quot;</description>
        <inlineHelpText>Code of the dealer that deliver the service</inlineHelpText>
        <label>Service Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Aftersales_Record</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Vehicle__c</fullName>
        <description>Attribute in Data Dictionary object Aftersales is &quot;Service_Vehicle&quot;</description>
        <label>Service Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Aftersales_Record</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To flag whether the aftersales record is valid</description>
        <label>Validity</label>
        <type>Checkbox</type>
    </fields>
    <label>Aftersales</label>
    <nameField>
        <label>Service No*</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aftersales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
</CustomObject>

src/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>Valid__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag to indicate whether the VIN is valid 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: Mouse Liu
Modify Reason: Just change the field type to Picklist with LOV &apos;Unknown Yes No&apos;
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_Valid“</description>
        <label>Validity</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Last_Service_Dealer__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Name of last service dealer
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_LastServiceDealer“</description>
        <inlineHelpText>Name of last service dealer</inlineHelpText>
        <label>Last Service Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships(Vehicle Relationship Last Service Dealer)</relationshipLabel>
        <relationshipName>Vehicle_Relationship_Last_Service_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is&quot;VehicleRel_VehicleID&quot;</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TriggerAftersalesTest.cls
/*
    Type:       Test class
    Purpose:    Test Class for TriggerAftersales.trigger
    User Story: US-CP-14
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-06
*/
@isTest
public class TriggerAftersalesTest{
    public static testMethod void testTriggerAftersales() {
        // Create Test User
        // User usr = testUtil.createUser('IB CSR', 'CAC IB CSR');
        
        // Create Dealer
        Account dealer = (Account)UtilTestData.createSobject(new Account(), 
            UtilTestData.ACCOUNT_RT_DEALER);
        
        // Create Person Account
        Account personAccount = (Account)UtilTestData.createSobject(new Account(), 
            UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
        
        // Create Vehicle
        Vehicle__c vehicle = (Vehicle__c)UtilTestData.createSobject(new Vehicle__c(), null);
        
        // Create Vehicle Relationship
        Vehicle_Relationship__c relationship = 
            new Vehicle_Relationship__c(Vehicle_ID__c = vehicle.Id);
        relationship = (Vehicle_Relationship__c)UtilTestData.createSobject(relationship, null);
        
        // Create Aftersales;
        Aftersales__c aftersales = new Aftersales__c(Service_Dealer__c = dealer.Id,
                                                     Service_Vehicle__c = vehicle.Id,
                                                     Service_Contact__c = personAccount.Id);
        aftersales = (Aftersales__c)UtilTestData.createSobject(aftersales, null);
      
        // Start Test
        Test.startTest();
        
        // Update aftersales
        aftersales.Valid__c = true;
        update aftersales;
       
        // Assert Updated personAccount Result
        personAccount = [SELECT Main_Dealer__c, Latest_Service_Dealer__c
                         FROM Account
                         WHERE Id = :personAccount.Id];
        System.assertEquals(personAccount.Main_Dealer__c, dealer.Id);
        System.assertEquals(personAccount.Latest_Service_Dealer__c, dealer.Id);
       
        // Assert Updated relationship Result
        relationship = [SELECT Last_Service_Dealer__c
                        FROM Vehicle_Relationship__c
                        WHERE Id = :relationship.Id];
        System.assertEquals(relationship.Last_Service_Dealer__c, dealer.Id);
                
        // Stop Test
        Test.stopTest();
    }
}