src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
        <picklist>
            <controllingField>Province__c</controllingField>
            <picklistValues>
                <fullName>安庆市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>蚌埠市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>亳州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>巢湖市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>池州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>滁州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>阜阳市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>合肥市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>淮北市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>淮南市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>黄山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>六安市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>马鞍山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宿州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>铜陵市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>芜湖市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宣城市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>昆山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>澳门特区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>福州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>金门县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>连江县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>龙岩市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>南平市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宁德市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>莆田市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>泉州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>三明市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>厦门市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>漳州市</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Province__c</fullName>
        <formula>TEXT( Dealer_City__r.Province__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Province</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Region__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Region of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_Region&quot;</description>
        <label>Dealer Region</label>
        <picklist>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Sales_Type__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: The sales type of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_SalesType&quot;</description>
        <label>Dealer Sales Type</label>
        <picklist>
            <picklistValues>
                <fullName>0=MBCL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1=Smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2=AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3=Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4=Star-Elite</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Service_Codes__c</fullName>
        <description>Dealer Services - based on the GSSN interface for the Dealer ActivityDefCodes

Feb-18-2012: Added by Rob and Falk
Attribute in Data Dictionary object Dealer is &quot;Dealer_Service&quot;</description>
        <label>Dealer Service Codes</label>
        <picklist>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSC Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
        <picklist>
            <picklistValues>
                <fullName>Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zhejiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tianjin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tibet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xinjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sichuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yunnan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chongqing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangdong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guizhou</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
</CustomObject>

src/classes/DealerSearchController.cls
/*
    Type:       Extension for DealerSearch Visualforce page 
    Purpose:    Search Dealer by specified filters
    User Story: US-DS-001
    Used By:    DealerSearch.page
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-04

*/
public with sharing class DealerSearchController {
    public Account dealer                   {get; set;}
    public List<Account> dealers            {get; set;}
    public String name                      {get; set;}
    public Boolean hasQueryResult           {get; set;}
    
    // Query return limit and Dealer's Record Type Name
    private final Integer QUERY_LIMIT = 200;
    private final String ACCOUNT_RT_DEALER = 'Dealer';
    
    // Account Address Fields Mapping with Dealer City
    private final Map<String, String> ADDRESS_FIELD_MAPPING = new Map<String, String> {
        'Dealer_Region__c' => 'Dealer_Region__c',
        'Province__c' => 'Province__c',
        'City_CN__c' => 'City_CN__c'
    };
    
    // Two Muti-Select Fields on Account
    private final List<String> MUTI_SELECT_FIELDS = new List<String> {
        'Dealer_Sales_Type__c',
        'Dealer_Service_Codes__c'
    };
    
    public DealerSearchController(Apexpages.StandardController con) {
        // We must assign the Dealer Record Type Id to the proxy account
        Id dealerRecordTypeId = UtilRecordType.getRecordTypeIdByName('Account', 
            this.ACCOUNT_RT_DEALER);
        dealer = new Account(RecordTypeId = dealerRecordTypeId);
        
        try {
            Account personAccount = [ SELECT Name, Dealer_Province__c,
                                             Dealer_Sales_Type__c, Dealer_Service_Codes__c,
                                             Dealer_Region__c, Province__c, City_CN__c
                                      FROM Account 
                                      WHERE Id = :con.getId()];
            
            // We only need pass the province and city to the search page
            dealer.Province__c = personAccount.Province__c;
            dealer.City_CN__c = personAccount.City_CN__c;
        }
        catch (QueryException e) {
            // If user open this from home page, it means, 
            // we don't need to pass province and city
            System.debug('User may open this page in the Home Page Custom Link.');
        }

        query();
    }
    
    // Get the SOQL Expr of DealerSearchColumns FieldSet fields
    private String getColumns() {
        String columns = '';
        for (Schema.FieldSetMember member : this.getFieldSetMembers()) {
            columns += member.getFieldPath() + ', ';
        }
        
        return columns;
    }
    
    // Get the FieldSet Members of Account FieldSet(DealerSearchColumns)
    private List<Schema.FieldSetMember> getFieldSetMembers() {
        return SObjectType.Account.FieldSets.DealerSearchColumns.getFields();
    }
    
    // Parse these two mutiselect value (Dealer_Sales_Type__c, Dealer_Service_Codes__c) 
    // to SOQL Expression: 
    private String parseMutiSelect(String fieldAPI) {
        String retValue = fieldAPI + ' INCLUDES (';
        List<String> parseValues = String.valueOf(dealer.get(fieldAPI)).split(';');
        for (String value : parseValues) {
            retValue += '\'' + value + '\',';
        }
        retValue = retValue.subString(0, retValue.length() - 1) + ') ';
        
        return retValue;
    }
    
    public void query() {
        // We must inculde the IsPsersonAccount in the SOQL, otherwise, 
        // we will get exception in debug log but not display on the page
        String querySOQL = 'SELECT ' + this.getColumns() + 'IsPersonAccount, Id FROM Account ' +
                           'WHERE RecordType.Name = :ACCOUNT_RT_DEALER AND ';

        // If Name filter is not null, add it into SOQL
        if (name != null && name != '') {
            querySOQL += 'Name LIKE \'%' + name + '%\' AND ';
        }
        
        // For loop the address fields, if not null, add it into SOQL
        for (String fieldAPI : this.ADDRESS_FIELD_MAPPING.keySet()) {
            // Get the AddressInfo
            Object obj = dealer.get(fieldAPI);
            
            if (obj != null) {
                String addressInfo = String.valueOf(obj);
                querySOQL += this.ADDRESS_FIELD_MAPPING.get(fieldAPI) + ' = \'' + 
                    addressInfo + '\' AND ';
            }
        }
        
        // If Dealer Sales Type is not null, add it into SOQL
        // If Dealer Service Codes is not null, add it into SOQL
        for (String fieldAPI : this.MUTI_SELECT_FIELDS) {
            if (dealer.get(fieldAPI) != null) {
                querySOQL += this.parseMutiSelect(fieldAPI) + ' AND ';
            }
        }
        
        querySOQL = querySOQL.subString(0, querySOQL.length() - 4) + 
            'ORDER BY Dealer_Region__c DESC NULLS LAST LIMIT ' + this.QUERY_LIMIT;
        System.debug(querySOQL);
        
        dealers = Database.query(querySOQL);
        
        // If no query result, system alert no search result.
        hasQueryResult = (dealers.size() > 0);
        if (!hasQueryResult) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 
                                   Label.CP_No_Search_Result));
        }
    }
    
    /*
    public void clear() {
        dealer = new Account();
        query();
    }
    */
}