src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Inquiry</fullName>
        <active>true</active>
        <businessProcess>Inquiry Process</businessProcess>
        <description>Customer Inquiry Case</description>
        <label>Inquiry</label>
    </recordTypes>
</CustomObject>

src/objects/SMS__c.object
<CustomObject>
    <description>Case: This object is used by VF page for ad hoc SMS, Hidden for all users.</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SMS(Dealer Name)</relationshipLabel>
        <relationshipName>SMS_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
</CustomObject>

src/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Detail__c</fullName>
        <label>Message Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SMSControllerExtensionTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
public class SMSControllerExtensionTest {

    public static testMethod void testSMSControllerExtension() 
    {
        // Testing the SMS Send
        ApexPages.standardController controller = new ApexPages.standardController(new SMS__c());
        
        // Add parameters to page URL
        String personAccountRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String dealerRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account customer = new Account(LastName = 'Acme Customer', Phone = '01088888888', RecordTypeId = personAccountRecordTypeId);
        insert customer;
        Account dealer = new Account(Name = 'Acme Dealer', Phone = '01088888888', RecordTypeId = dealerRecordTypeId);
        insert dealer;
        //String accountId = [Select Id, PersonMobilePhone, Name From Account where isPersonAccount = true Limit 1][0].Id;
        ApexPages.currentPage().getParameters().put('accountId',customer.Id);
        ApexPages.currentPage().getParameters().put('retURL',customer.Id);
        
        // Test click SMS button from Account
        // Instantiate a new controller extension with all parameters in the page
        SMSControllerExtension extension = new SMSControllerExtension(controller);
        extension.sms.Dealer__c = dealer.Id;
        extension.templateId = [select Id, Name, Message_Detail__c from Template__c where RecordType.SObjectType='Template__c' and RecordType.Name='SMS' and Active__c = true limit 1].Id;
        List<SelectOption> Templates = extension.getTemplates();
        extension.parseTemplateMessage();
        String message = extension.optimzeContent('temp{DEALER_NAME}temp');
    
        // Send SMS
        extension.send();
        
        Task t = [Select t.WhoId, t.WhatId, t.Subject, t.Status, t.SMS_Content__c From Task t Where WhatId=:customer.Id and SMS_Content__c=:extension.templateMessage];
        System.assertEquals(t.Subject, 'SMS');
        System.assertEquals(t.Status, 'Closed');
        System.assertEquals(t.WhoId, [Select Id From Contact Where accountId = :customer.Id limit 1].Id);
        
        //Test click SMS button from Case
        String inquiryRecordTypeId = Schema.SObjectType.case.getRecordTypeInfosByName().get('Inquiry').getRecordTypeId();
        Case cas = new Case(AccountId = customer.Id, Subject = 'acme', RecordTypeId = inquiryRecordTypeId);
        insert cas;
        ApexPages.currentPage().getParameters().put('caseId', cas.Id);
        ApexPages.currentPage().getParameters().put('accountId', customer.Id);
        ApexPages.currentPage().getParameters().put('retURL', cas.Id);
        
        extension = new SMSControllerExtension(controller);
        extension.sms.Dealer__c = dealer.Id;
        extension.templateId = [select Id, Name, Message_Detail__c from Template__c where RecordType.SObjectType='Template__c' and RecordType.Name='SMS' and Active__c = true limit 1].Id;
        Templates = extension.getTemplates();
        extension.parseTemplateMessage();
        message = extension.optimzeContent('temp{DEALER_NAME}temp');
        
        // Send SMS
        extension.send();
        
        t = [Select t.WhoId, t.WhatId, t.Subject, t.Status, t.SMS_Content__c From Task t Where WhatId = :cas.Id and SMS_Content__c=:extension.templateMessage];
        System.assertEquals(t.Subject, 'SMS');
        System.assertEquals(t.Status, 'Closed');
        Contact personContact = [select Id from Contact where AccountId = :customer.Id limit 1];
        System.assertEquals(t.WhoId, personContact.Id);
    }
}