src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DMS_Address__c</fullName>
        <description>DMS address of the customer delivered by GSSN</description>
        <label>DMS Address</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Successful_Call_Office_Phone__c</fullName>
        <description>To record the last successful call time for office phone of the customer</description>
        <label>Last Successful Call (Office Phone)</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src/objects/eDM__c.object
<CustomObject>
    <description>Case: used for Ad-hoc eDM VF page display. Hidden for all users.</description>
    <fields>
        <fullName>eDM_Template__c</fullName>
        <label>eDM Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>eDM</relationshipLabel>
        <relationshipName>eDM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>eDM</label>
    <nameField>
        <displayFormat>eDM-{000000}</displayFormat>
        <label>eDM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eDM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
</CustomObject>

src/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <fields>
        <fullName>Car_Series__c</fullName>
        <label>Car Series</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ML-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>e-Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Brochure plus Price List</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EDMControllerExtensionTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class EDMControllerExtensionTest {

    public static testMethod void testMyController() {
        
        User user1 = UtilTestData.createUser('IB CSR','CAC IB CSR');
        
        System.debug('-------user1-------:'+user1);
        
        System.runAs ( user1 ) {
        
        
            // Testing the eDM Send
            ApexPages.standardController controller = new ApexPages.standardController(new eDM__c());
            
            // Add parameters to page URL
            System.debug('--------Begin-------');
            Account customer = new Account(
                                         Phone = '13300000000',
                                         Last_Successful_Call_Office_Phone__c = System.today() - 10,
                                         DMS_Address__c = 'dmsaddress1',
                                         PersonEmail = 'test@daimler.com');
    
            customer = (Account)UtilTestData.createSobject(customer, UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);   
            
            
            ApexPages.currentPage().getParameters().put('accountId',customer.Id);
            
            //Create new eDM Template
            String rdid = [Select r.SobjectType, r.Name, r.Id From RecordType r Where Name='eDM' and SobjectType='Template__c'][0].Id;
            Template__c edmt = new Template__c(Type__c='Price List', Car_Series__c='A-Class', RecordTypeId=rdid);
            Insert edmt;
            edmt = [Select Id,Name From Template__c Where Id=:edmt.Id];
            System.assertEquals(edmt.Name,'A-Class - Price List');
            
            // Test click eDM button from Account
            // Instantiate a new controller extension with all parameters in the page
            EDMControllerExtension extension = new EDMControllerExtension(controller);
            extension.edm.eDM_Template__c = edmt.Id;
            
            // Send eDM
            extension.send();
            
            Task t = [Select t.WhoId, t.WhatId, t.Subject, t.Status, t.eDM_Template__c,Email_Address__c,OwnerId From Task t Where WhatId=:customer.Id and eDM_Template__c=:edmt.Name];
            System.assertEquals(t.Subject,'eDM');
            System.assertEquals(t.Status,'Closed');
            System.assertEquals(t.OwnerId,user1.Id);
            System.assertEquals(t.Email_Address__c,'test@daimler.com');
            System.assertEquals(t.WhoId,[Select Id From Contact Where accountId = :customer.Id].Id);
            
                        
            //Test click eDM button from Case
            Case case1 = new Case(AccountId=customer.Id, Subject='Case-'+Datetime.now().formatLong());
            insert case1;
            ApexPages.currentPage().getParameters().put('caseId',case1.Id);
            
            extension = new EDMControllerExtension(controller);
            //extension.edm.eDM_Template__c = 'Price List' + Datetime.now().formatLong();
            
            // Send eDM
            extension.send();
            
            t = [Select t.WhoId, t.WhatId, t.Subject, t.Status, t.eDM_Template__c,Email_Address__c,OwnerId From Task t Where WhatId=:case1.Id and eDM_Template__c=:edmt.Name];
            System.assertEquals(t.Subject,'eDM');
            System.assertEquals(t.Status,'Closed');
            System.assertEquals(t.OwnerId,user1.Id);
            System.assertEquals(t.Email_Address__c,'test@daimler.com');
            System.assertEquals(t.WhoId,[Select Id From Contact Where accountId = :customer.Id].Id);
            System.assertEquals(t.WhatId,case1.Id);
        
            // Cover Exception
	        //PageReference pr  = new PageReference('/apex/EDMSendResult?accountId='+customer.Id);
	        //Test.setCurrentPage(pr);
	        controller = new ApexPages.standardController(new eDM__c());
	        extension = new eDMControllerExtension(controller);
	      	// runAs readonly user
	        User user2 = UtilTestData.createUser('IB CSR','Read Only');
	        System.runAs ( user2 ) {  
	            extension.send();
	        }
        }
    }
}