src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
        <picklist>
            <controllingField>Province__c</controllingField>
            <picklistValues>
                <fullName>安庆市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>蚌埠市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>亳州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>巢湖市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>池州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>滁州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>阜阳市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>合肥市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>淮北市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>淮南市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>黄山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>六安市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>马鞍山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宿州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>铜陵市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>芜湖市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宣城市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>昆山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>澳门特区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>福州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>金门县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>连江县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>龙岩市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>南平市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>宁德市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>莆田市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>泉州市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>三明市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>厦门市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>漳州市</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Address_CN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Main address field, line 1 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: Lio Huang
Modify Reason: Dealer Address (Chinese) from GSSN
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_AddressCN&quot;</description>
        <label>Dealer Address CN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Province__c</fullName>
        <formula>TEXT( Dealer_City__r.Province__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Province</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Mobile__c</fullName>
        <description>Second mobile phone number of the customer</description>
        <label>Second Mobile</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Dealer__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer in regards of complaint 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Case Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Dealer)</relationshipLabel>
        <relationshipName>Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/SMS__c.object
<CustomObject>
    <description>Case: This object is used by VF page for ad hoc SMS, Hidden for all users.</description>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>Customer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SMS(Dealer Name)</relationshipLabel>
        <relationshipName>SMS_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Mobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Secondary Mobile</label>
        <type>Checkbox</type>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
</CustomObject>

src/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Detail__c</fullName>
        <label>Message Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SMSControllerExtension.cls
/*
    Type:       controller
    Purpose:    SMSSendResult General Controller
    User Story: US-SMS-001 - Send SMS content to customer

    Used By:    VF Page - SMSSendResult.page
    ---------------------------------------------------------------
    History:

    07-Mar-2013 Sinow zhang (Nttdata)    Created
*/

public class SMSControllerExtension 
{
    /* Public Properties */
    public SMS__c sms { get; set; }
    public String templateId { get; set; }
    public String templateMessage { get; set; }
    public Account customer {get;set;}
    
    /* Private Properties */
    private Case caseObject {get;set;}
    private Map<String, String> templateMap { get; set; }
    private Map<String, String> templateNameMap { get; set; }
    private ApexPages.standardController controller {get;set;}

    /* Public Methods */
    public PageReference send() 
    {
        if(customer == null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You have to select one customer before send SMS.'));
            return null;
        }
        else if(customer.Second_Mobile__c == null && customer.PersonMobilePhone == null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Customer Mobile Phone Number is null, Please fill it first.'));
        }
        if(templateId == null || templateId == '' || templateId == 'None')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You have to select one SMS template.'));
            return null;
        }
        if(templateMessage == '' || templateMessage == null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'SMS Preview is null, Please fulfill it.'));
            return null;
        }
        
        //create task
        createActivity();

        // use the standard controller to perform the save and redirect
        //return new PageReference('/' + customer.Id);
        return controller.cancel();
    }

    //set value to template message
    public PageReference parseTemplateMessage()
    {
        if(templateMap.containsKey(templateId)) 
        {
            if(templateMap.get(templateId).indexOf('{DEALER_') != -1)
            {
                if(sms.Dealer__c == null)
                {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You have to select one Dealer.'));
                    return null;
                }
                templateMessage = optimzeContent(templateMap.get(templateId));
            }
            else
            {
                templateMessage = templateMap.get(templateId);
            }
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You have to select one SMS template.'));
            templateMessage = '';
        }
        return null;
    }

    //parse merge fields for message
    public String optimzeContent(String temp)
    {
        String handledContent = temp;
        if(handledContent.indexOf('{') != -1)
        {
            do
            {
                Integer mergeIndexStart = handledContent.indexOf('{');
                Integer mergeIndexEnd = handledContent.indexOf('}');
                String mergeObjectField = handledContent.subString(mergeIndexStart + 1, mergeIndexEnd);
                if(mergeObjectField.indexOf('_') != -1)
                {
                    String mergeObject = mergeObjectField.subString(0, mergeObjectField.indexOf('_'));
                    String mergeField = mergeObjectField.subString(mergeObjectField.indexOf('_') + 1);
                    if(mergeObject == 'DEALER' && sms.Dealer__c != null)
                    {
                        if(mergeField != 'ADDRESS')
                        {
                            String dealerQuery = 'select ' + mergeField + ' from Account where Id = \'' + sms.Dealer__c + '\' limit 1';
                            List<Account> dealerQuerys = Database.query(dealerQuery);
                            handledContent = handledContent.subString(0, mergeIndexStart) + dealerQuerys[0].get(mergeField) + handledContent.subString(mergeIndexEnd + 1);
                        }
                        else
                        {
                            Account dealerInfo = [select Dealer_Address_CN__c, City_CN__c, Dealer_Province__c from Account where Id = :sms.Dealer__c limit 1];
                            handledContent = handledContent.subString(0, mergeIndexStart) + dealerInfo.Dealer_Province__c + dealerInfo.City_CN__c + dealerInfo.Dealer_Address_CN__c + handledContent.subString(mergeIndexEnd + 1);
                        }
                    }
                    else
                    {
                        handledContent = handledContent.subString(0, mergeIndexStart) + ' ' + handledContent.subString(mergeIndexEnd + 1);
                    }
                }
                else
                {
                    handledContent = handledContent.subString(0, mergeIndexStart) + ' ' + handledContent.subString(mergeIndexEnd + 1);
                }
            }while(handledContent.indexOf('{') != -1);
        }
        return handledContent;
    }   

    //returns list options of templates
    public List<SelectOption> getTemplates() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('None','--None--'));
        templateNameMap = new Map<String, String>();
        templateMap = new Map<String, String>();
        for(Template__c tem : [select Id, Name, Message_Detail__c from Template__c where RecordType.SObjectType='Template__c' and RecordType.Name='SMS' and Active__c = true])
        {
            options.add(new SelectOption(tem.Id, tem.Name));
            templateNameMap.put(tem.Id, tem.Name);
            templateMap.put(tem.Id, tem.Message_Detail__c);
        }
        return options;
    }

    /* Private Methods */
    private void createActivity()
    {
        if(caseObject != null)
        {
            smsTask.WhatId = caseObject.Id;
            if(customer != null)
            {
                Contact personContact = [select Id from Contact where AccountId = :customer.Id limit 1];
                smsTask.WhoId = personContact.Id;
            }
        }
        else
        {
            smsTask.WhatId = customer.id;
            Contact personContact = [select Id from Contact where AccountId = :customer.Id limit 1];
            smsTask.WhoId = personContact.Id;
        }
        
        if(sms.Dealer__c != null)
        {
            Account tempDealer = [select Id, Name from Account where Id = :sms.Dealer__c];
            smsTask.Dealer_Name__c = tempDealer.Name;
        }
        smsTask.SMS_Content__c = templateMessage;
        if(sms.Mobile__c)
        {
            smsTask.Phone__c = customer.PersonMobilePhone;
        }
        else if(sms.Secondary_Mobile__c)
        {
            smsTask.Phone__c = customer.Second_Mobile__c;
        }

        try
        {
            insert smsTask;
        }
        catch(Exception e)
        {
            ApexPages.addMessages(e);
        }
    }
    
    private Task smsTask 
    {
        get
        {
            if(smsTask == null)
            {
                smsTask = new Task();
                smsTask.Subject = 'SMS';
                smsTask.Status = 'Closed';
                smsTask.Activity_Status__c = 'Sent';
                smsTask.RecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
            }
            return smsTask;
        }
        set;
    }

    /* Static initialisers */
  
    public SMSControllerExtension(ApexPages.StandardController stdController) 
    {
        // constructor
        controller = stdController;       
        this.sms = (SMS__c)stdController.getRecord();
        if(sms == null)
        {
            sms = new SMS__c();
        }        
        
        //set account
        String accountId = ApexPages.currentPage().getParameters().get('accountId');

        if(accountId != null && accountId != '')
        {
            List<Account> aList = [Select Id, Name, PersonMobilePhone, Second_Mobile__c From Account Where Id = :accountId];
            if(aList.size() == 1)
            {
                customer = aList[0];
                sms.CustomerName__c = customer.Name;
                if(customer.Second_Mobile__c == null && customer.PersonMobilePhone == null)
                {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Customer Mobile Phone Number is null, Please fill it first.'));
                }
                if(customer.PersonMobilePhone != null && customer.PersonMobilePhone != '')
                {
                    sms.Mobile__c = true;
                }
                else if(customer.Second_Mobile__c != null && customer.Second_Mobile__c != '')
                {
                    sms.Secondary_Mobile__c = true;
                }
            }
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You have to select one customer before send SMS.'));
        }
        
        //set case if SMS from case
        String caseId = ApexPages.currentPage().getParameters().get('caseId');

        if(caseId != null && caseId != '')
        {
            caseObject = [Select Id, Account.Name, AccountId, Case_Dealer__c From Case Where Id = :caseId];
            if(caseObject.Case_Dealer__c != null)
            {
                sms.Dealer__c = caseObject.Case_Dealer__c;
            }
        }
    }
}