src/objects/Attribute__c.object
<CustomObject>
    <description>Knowledge: this object is used to store Car Attribute</description>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <label>Attribute Category</label>
        <picklist>
            <picklistValues>
                <fullName>基本参数</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>扩展参数</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>价格</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>发动机和性能</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>燃油消耗</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>地盘和车轮</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>尺寸和重量</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Car Attribute</label>
    <nameField>
        <label>Car Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Car_Model__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model info to be used in DM and Car Model comparison.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>A160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B180 BlueEFFICIENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 BlueEFFICIENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Sports Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 fashion model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 luxury model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 豪华型 夜行独享版</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C180K 经典型 (CKD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C180K 经典型</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 CGI优雅型</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 CGI时尚型</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 Entry Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 优雅型</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 旅行轿车</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 fashion model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 时尚型旅行轿车</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 luxury model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K grace model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K fashion model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K sports car (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 grace model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 fashion model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 sports car (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240 (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240A fashion model (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240E  grace model (not current series)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ML-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Class</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Model</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Car_Model_Attribute__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model Attribute info to be used in Car Model comparison.</description>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <formula>TEXT(Attribute__r.Attribute_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <formula>Text(Attribute__r.Attribute_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Car Model Attribute</relationshipLabel>
        <relationshipName>Car_Model_Attribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>text(Car_Model__r.Brand__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Car_Model__c</fullName>
        <label>Car Model</label>
        <referenceTo>Car_Model__c</referenceTo>
        <relationshipLabel>Car Model Attribute</relationshipLabel>
        <relationshipName>Car_Model_Attribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>text( Car_Model__r.Model__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <formula>text( Car_Model__r.Series__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Series</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Car Model Attribute</label>
    <nameField>
        <displayFormat>CMA{000000}</displayFormat>
        <label>Car Model Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Model Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CarModelComparisonController.cls
/*
    Type:       Extension for CarModelComparison Visualforce page 
    Purpose:    Compare the attributes of the chosen three cars
    User Story: US-Knowledge-003
    Used By:    CarModelComparison.page
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-07
*/
public with sharing class CarModelComparisonController {
    public Map<String, List<String>> typeWithNamesMap   {get; set;}
    public List<Integer> proxySequences                 {get; set;}
    public List<Car_Model_Attribute__c> proxies         {get; set;}
    public List<Integer> chosenProxySequences           {get; set;}
    public List<Car_Model_Attribute__c> chosenProxies   {get; set;}
    public Map<String, Car_Model__c> carModelsMap       {get; set;}

    // Used to display Car Model Picture in related Attachment
    public Map<Id, String> modelId2AttachmentIdMap      {get; set;}
    
    // Attribute Type + Attr Name + Car Model Id => Car Model Attribute Value
    public Map<String, String> combineMap               {get; set;}
    
    // Define Picture Attachment File Extension
    private final Set<String> PICTURE_EXTENSIONS = 
        new Set<String> {
            '.BMP', 
            '.JPG', 
            '.JPEG', 
            '.PNG',
            '.GIF'
    };

    // Numbers of Car Models to compare
    // You can change it to more than 3 cars
    private final Integer NUM_OF_CAR_MODELS = 3;

    public CarModelComparisonController() {
        // Initiate cars
        proxySequences = new List<Integer>();
        proxies = new List<Car_Model_Attribute__c>();
        for (Integer i = 0; i < this.NUM_OF_CAR_MODELS; i++) {
            proxySequences.add(i);
            proxies.add(new Car_Model_Attribute__c());
        }
        
        proxies[0].Car_Model__c = 'a13N0000001Xv7o';
        proxies[1].Car_Model__c = 'a13N0000001XwGR';
        proxies[2].Car_Model__c = 'a13N0000001Xuxm';
        //proxies[3].Car_Model__c = 'a13N0000001XwWK';
        //proxies[4].Car_Model__c = 'a13N0000001GtDC';
        
        // Initiate chosenProxies, catWithTypes and combineMap
        typeWithNamesMap = new Map<String, List<String>>();
        combineMap = new Map<String, String>();
        chosenProxies = new List<Car_Model_Attribute__c>();
        
        this.pouplateCompareResult();
    }

    public void pouplateCompareResult() {
        // Populate chosenProxies
        chosenProxies.clear();        
        for (Car_Model_Attribute__c proxy : proxies) {
            if (proxy.Car_Model__c != null) {
                chosenProxies.add(proxy);
            }
        }
        System.debug('chosenProxies=>' + chosenProxies);
        chosenProxySequences = new List<Integer>();
        for (Integer i = 0; i< chosenProxies.size(); i++) {
            chosenProxySequences.add(i);
        }
        
        // Get the Car Model Ids from proxies
        Set<Id> carModelIds = new Set<Id>();
        for (Car_Model_Attribute__c proxy : proxies) {
            carModelIds.add(proxy.Car_Model__c);
        }

        // Populate combineMap and typeWithNamesMap
        List<Car_Model_Attribute__c> junkRecords = this.getJunkRecords(carModelIds);
        
        Set<String> attributeTypes = new Set<String>();
        carModelsMap = new Map<String, Car_Model__c>();
        for (Car_Model_Attribute__c junkRecord : junkRecords) {
            attributeTypes.add(junkRecord.Attribute_Type__c);
            carModelsMap.put(junkRecord.Car_Model__c, junkRecord.Car_Model__r);
        }

        for (String attributeType : attributeTypes) {
            Set<String> attributeNameSet = new Set<String>();
            for (Car_Model_Attribute__c junkRecord : junkRecords) {
                // Populate value in typeWithNamesMap by key
                if (attributeType == junkRecord.Attribute_Type__c) {
                    attributeNameSet.add(junkRecord.Attribute__r.Name);
                }
                
                // Populate combineMap
                if (junkRecord.Value__c != null) {                
                    combineMap.put(attributeType + junkRecord.Attribute__r.Name + 
                        junkRecord.Car_Model__c, junkRecord.Value__c);
                }
            }
            
            // Populate typeWithNamesMap
            typeWithNamesMap.put(attributeType, new List<String>(attributeNameSet));
        }
        
        // Prevent Map key <key> not found in map
        // http://salesforce.stackexchange.com/questions/5190/how-to-handle-maps-with-no-key-match
        // Populate the value that is null with blank.
        for (String type : typeWithNamesMap.keySet()) {
            for (String name : typeWithNamesMap.get(type)) {
                for (Car_Model_Attribute__c attr : junkRecords) {
                    String key = type + name + attr.Car_Model__c;
                    if (!combineMap.containsKey(key)) {
                        combineMap.put(key, '');
                    }
                }
            }
        }
        
        System.debug(combineMap);

        // Populate modelId2AttachmentIdMap
        modelId2AttachmentIdMap = new Map<Id, String>();
        for (Car_Model__c model : [SELECT Id, 
                                        (SELECT Id, Name
                                         FROM Attachments)
                                   FROM Car_Model__c
                                   WHERE Id IN :carModelIds]) {

            Attachment pictureAtt;
            for (Attachment att : model.Attachments) {
                String extensionName = att.Name.subString(att.Name.lastIndexOf('.'),  
                    att.Name.length());

                if (PICTURE_EXTENSIONS.contains(extensionName.toUpperCase())) {
                    pictureAtt = att;
                    break;
                }
            }

            modelId2AttachmentIdMap.put(model.Id, 
                pictureAtt == null ? 'empty' : pictureAtt.Id);
        }

    }
    
    public List<Car_Model_Attribute__c> getJunkRecords(Set<Id> carModelIds) {
        List<Car_Model_Attribute__c> junkRecords;
        junkRecords = [SELECT Id, Attribute_Type__c, Attribute_Category__c,
                              Attribute__r.Name, Model__c, Value__c,
                              Car_Model__c, Car_Model__r.Brand__c,
                              Car_Model__r.Series__c,
                              Car_Model__r.Model__c,
                              Car_Model__r.Description__c
                       FROM Car_Model_Attribute__c
                       WHERE Car_Model__c IN :carModelIds
                       ORDER BY Attribute_Type__c, Attribute__r.Name, Car_Model__c];
                  
        return junkRecords;
    }
    
    public void compare() {
        this.pouplateCompareResult();
    }
    
    public String getValueByParam(String param) {
        String value = ApexPages.currentPage().getParameters().get(param);
        return value;
    }
    
    public PageReference cancel() {
        String retURL = this.getValueByParam('retURL');
        return new PageReference(retURL);
    }
}