src/objects/Attribute__c.object
<CustomObject>
    <description>Knowledge: this object is used to store Car Attribute</description>
    <label>Car Attribute</label>
    <nameField>
        <label>Car Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Car_Model__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model info to be used in DM and Car Model comparison.</description>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Model</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Car_Model_Attribute__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model Attribute info to be used in Car Model comparison.</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Car Model Attribute</relationshipLabel>
        <relationshipName>Car_Model_Attribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Car_Model__c</fullName>
        <label>Car Model</label>
        <referenceTo>Car_Model__c</referenceTo>
        <relationshipLabel>Car Model Attribute</relationshipLabel>
        <relationshipName>Car_Model_Attribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Car Model Attribute</label>
    <nameField>
        <displayFormat>CMA{000000}</displayFormat>
        <label>Car Model Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Model Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
</CustomObject>

src/classes/CarModelComparisonControllerTest.cls
/*
    Type:       Test Class
    Purpose:    Test Class CarModelComparisonController
    User Story: US-Knowledge-003
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-11
*/
@isTest
public class CarModelComparisonControllerTest {
	public static testMethod void testCarModelComparison() {
		// Create Person Account
        Account personAccount = (Account)UtilTestData.createSobject(new Account(), 
            UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);

		// Create Car Models
		List<Car_Model__c> carModels = new List<Car_Model__c>();
		for (Integer i = 0; i < 3; i++) {
			carModels.add(new Car_Model__c());
		}
		carModels = (List<Car_Model__c>)UtilTestData.createSobjects(carModels, null);

		// Create Attributes
		List<Attribute__c> attrs = new List<Attribute__c>();
		for (Integer i = 0; i < UtilTestData.BATCH_SIZE; i++) {
			attrs.add(new Attribute__c());
		}
		attrs = (List<Attribute__c>)UtilTestData.createSobjects(attrs, null);

		// Create Car Model Attributes by attributes and car models
		List<Car_Model_Attribute__c> modelAttrs = new List<Car_Model_Attribute__c>();
		for (Integer i = 0; i < UtilTestData.BATCH_SIZE; i++) {
			for (Car_Model__c model : carModels) {
				Car_Model_Attribute__c modelAttr = new Car_Model_Attribute__c(
	                Car_Model__c = model.Id,
	                Attribute__c = attrs[i].Id
	            );
	            modelAttrs.add(modelAttr);
	        }
		}
		modelAttrs = (List<Car_Model_Attribute__c>)UtilTestData.createSobjects(modelAttrs, null);

		// Test Start
        Test.startTest();

        PageReference pr = new PageReference('/apex/CarModelComparison/?retURL=/' + 
            personAccount.Id);
        Test.setCurrentPage(pr);
        CarModelComparisonController comparison = new CarModelComparisonController();
        
        for (Integer i = 0; i < 3; i++) {
        	comparison.proxies[i].Car_Model__c = carModels[i].Id;
        }

        comparison.compare();
        System.assert(comparison.chosenProxies.size() == 3);

        comparison.cancel();

		// Test Stop
		Test.stopTest();
	}
}