src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>DM_Material__c</fullName>
        <label>DM Material</label>
        <referenceTo>DM_Material__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <description>Used only for Campaign Execution record type. To lookup Template object to define Callscript, eDM name, or SMS template based on the Execution Type.</description>
        <inlineHelpText>Select Callscript, eDM name, or SMS template based on the Execution Type</inlineHelpText>
        <label>Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Campaign Executions</relationshipLabel>
        <relationshipName>Campaign_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Task_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Task Generated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/DM_Material__c.object
<CustomObject>
    <description>Case: Track the Material used by DM Request</description>
    <label>DM Material</label>
    <nameField>
        <label>DM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Material</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>DM</fullName>
        <active>true</active>
        <label>DM</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
</CustomObject>

src/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UtilCampaignTaskGeneration.cls
/*
    Type:       Apex Class
    Purpose:    Define methods used in trigger.DearlerOffering
    User Story: US-Cpn-018, US-Cpn-019, US-Cpn-020, US-Cpn-021
    Used By:    TriggerCampaign.trigger
    ---------------------------------------------------------------
    History:
    
	25-Mar-2013 Jorry Chen (Breakingpoint)    Created
*/

public Class UtilCampaignTaskGeneration{
	// get all campaign Members
	public static List<Campaign> getTaskMembers(List<Campaign> cpList) {
		if(cpList.size() > 0) {
			List<ID> cpIdList = new List<ID>();
			for(Campaign cp : cpList) {
				cpIdList.add(cp.Id);
			}
			
			return [select id, Name, Template__c, DM_Material__c, 
								(select id, ContactId, LeadId, Task_Generated__c from CampaignMembers) 
							from Campaign
							where id in :cpIdList];
		} else {
			return null;
		}
	}
	
	//generate OB call tasks US-018
	public static void generateTasksOBCall(List<Campaign> cpList) {
		List<Task> taskList = new List<Task>();
		Map<String, Schema.RecordTypeInfo> taskRecordTypeMap = Schema.SObjectType.Task.getRecordTypeInfosByName();
		List<User> userList = [select id, name from User where UserRole.Name = 'OB TL'];
		List<CampaignMember> cpMemberList = new List<CampaignMember>();
		if(cpList.size() > 0) {			
			for(Campaign cp : cpList) {
				for(CampaignMember cpMember : cp.CampaignMembers) {
					// check whether the member has realted task.
					if(!cpMember.Task_Generated__c) {
						for(User u : userList) {
						taskList.add(new Task(Subject= 'OB Call', 
												RecordTypeId = taskRecordTypeMap.get('OB Call').getRecordTypeId(),
												OwnerId = u.Id,
												Status_del__c = 'Open', 
												WhoId = (cpMember.ContactId == null ? cpMember.LeadId : cpMember.ContactId),
												WhatId = (cpMember.ContactId == null ? null : cp.Id),
												ActivityDate = date.today()));
						}
						cpMemberList.add(new CampaignMember(id=cpMember.Id, Task_Generated__c = true));
					}
					
				}
			}
		}
		
		Savepoint sp = Database.setSavepoint();
		try {
			if(taskList.size() > 0) insert taskList;
			if(cpMemberList.size() > 0) update cpMemberList;
		} catch(exception ex) {
    		Database.rollback(sp);
    		System.debug('create task failed : ' + ex);  			
		}
	}
	
	
	//generate eDM tasks  US-019
	public static void generateTaskseDM(List<Campaign> cpList) {
		List<Task> taskList = new List<Task>();
		Map<String, Schema.RecordTypeInfo> taskRecordTypeMap = Schema.SObjectType.Task.getRecordTypeInfosByName();
		List<User> userList = [select id, name from User where UserRole.Name = 'OB TL'];
		List<CampaignMember> cpMemberList = new List<CampaignMember>();
		if(cpList.size() > 0) {			
			for(Campaign cp : cpList) {
				for(CampaignMember cpMember : cp.CampaignMembers) {
					// check whether the member has realted task.
					if(!cpMember.Task_Generated__c) {
						for(User u : userList) {
						taskList.add(new Task(Subject= 'OB Call', 
												RecordTypeId = taskRecordTypeMap.get('OB Call').getRecordTypeId(),
												OwnerId = u.Id,
												Status_del__c = 'Open', 
												WhoId = (cpMember.ContactId == null ? cpMember.LeadId : cpMember.ContactId),
												WhatId = (cpMember.ContactId == null ? null : cp.Id),
												ActivityDate = date.today()));
						}
						cpMemberList.add(new CampaignMember(id=cpMember.Id, Task_Generated__c = true));
					}
					
				}
			}
		}
		
		Savepoint sp = Database.setSavepoint();
		try {
			if(taskList.size() > 0) insert taskList;
			if(cpMemberList.size() > 0) update cpMemberList;
		} catch(exception ex) {
    		Database.rollback(sp);
    		System.debug('create task failed : ' + ex);  			
		}
	}
	
	//generate SMS tasks
	
	//generate DM tasks
}