src/objects/DM_Material__c.object
<CustomObject>
    <description>Case: Track the Material used by DM Request</description>
    <fields>
        <fullName>SentTotal__c</fullName>
        <description>/*
Created by:  Chris.Huang
Used by:  Chris.Huang
Function: When DM Request Status changed to &apos;Sent&apos;, this field auto add 1.
Used in: Trigger, Formular

Modify History
Modify By: 
Modify Reason: 
*/</description>
        <label>Sent Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DM Material</label>
    <nameField>
        <label>DM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Material</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DM_Request__c.object
<CustomObject>
    <description>Case: Track the DM Request. This is also used by Campaign for bulk DM Request</description>
    <fields>
        <fullName>Actual_DM_Material1__c</fullName>
        <label>Actual DM Material1</label>
        <referenceTo>DM_Material__c</referenceTo>
        <relationshipLabel>DM Request (Actual DM Material1)</relationshipLabel>
        <relationshipName>DM_Fulfill</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_DM_Material2__c</fullName>
        <label>Actual DM Material2</label>
        <referenceTo>DM_Material__c</referenceTo>
        <relationshipLabel>DM Request (Actual DM Material2)</relationshipLabel>
        <relationshipName>DM_Fulfill1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_DM_Material3__c</fullName>
        <label>Actual DM Material3</label>
        <referenceTo>DM_Material__c</referenceTo>
        <relationshipLabel>DM Request (Actual DM Material3)</relationshipLabel>
        <relationshipName>DM_Fulfill2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DM Request</label>
    <nameField>
        <displayFormat>DMR-{000000}</displayFormat>
        <label>DM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DM Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DMRequestTriggerHandler.cls
/*
    Type:       Apex Class
    Purpose:    Define methods used in DMMaterialTrigger
    User Story: US-DM-004
    Used By:    DMMaterialTrigger.trigger
    ---------------------------------------------------------------
    History:
    
    11-Mar-2013 Chris Huang (Breakingpoint)    Created
*/

public class DMRequestTriggerHandler { 
    

    public static void updateDaterialSentTotal(List<DM_Request__c> newList, List<DM_Request__c> oldList){
        
        System.debug('---------enter--------'); 
        
        map<Id, DM_Request__c> oldMap = new map<Id, DM_Request__c>();
        if(oldList!=null && oldList.size()>0){
            for(DM_Request__c dmr : oldList){
                oldMap.put(dmr.Id,dmr);
            }
        }
        
        System.debug('---------newList.size()---------'+newList.size());
        
        if(newList!=null && newList.size()>0){
            
            map<Id, Integer> updateMap = new map<Id,Integer>();
            
            for(DM_Request__c dmr : newList){

                if(dmr.Status__c == 'Sent' && (!oldMap.containsKey(dmr.Id) || oldMap.get(dmr.Id).Status__c!=dmr.Status__c)){
                    
                    if(dmr.Actual_DM_Material1__c!=null){
                        if(!updateMap.containsKey(dmr.Actual_DM_Material1__c)){
                            updateMap.put(dmr.Actual_DM_Material1__c,0);
                        }
                        Integer i = updateMap.get(dmr.Actual_DM_Material1__c) + 1;
                        updateMap.put(dmr.Actual_DM_Material1__c,i);
                    }
                    
                    if(dmr.Actual_DM_Material2__c!=null){
                        if(!updateMap.containsKey(dmr.Actual_DM_Material2__c)){
                            updateMap.put(dmr.Actual_DM_Material2__c,0);
                        }
                        Integer i = updateMap.get(dmr.Actual_DM_Material2__c) + 1;
                        updateMap.put(dmr.Actual_DM_Material2__c,i);
                    }
                    
                    if(dmr.Actual_DM_Material3__c!=null){
                        if(!updateMap.containsKey(dmr.Actual_DM_Material3__c)){
                            updateMap.put(dmr.Actual_DM_Material3__c,0);
                        }
                        Integer i = updateMap.get(dmr.Actual_DM_Material3__c) + 1;
                        updateMap.put(dmr.Actual_DM_Material3__c,i);
                    }
                               
                }//end if
                                
            }//end for
            
            System.debug('---------updateMap.size()--------'+updateMap.size());
            
            if(updateMap.size()>0){
            
                List<DM_Material__c> updateList = [Select Id, SentTotal__c From DM_Material__c Where Id in :updateMap.keySet()];
                
                for(DM_Material__c dmm : updateList){
                    if(dmm.SentTotal__c==null){
                        dmm.SentTotal__c = 0;
                    }
                    dmm.SentTotal__c += updateMap.get(dmm.Id);
                }
                
                if(updateList.size()>0){

                	update updateList;                      
      
                }
            
            }
        }   
    }

}