src/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>Valid__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag to indicate whether the VIN is valid 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: Mouse Liu
Modify Reason: Just change the field type to Picklist with LOV &apos;Unknown Yes No&apos;
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_Valid“</description>
        <label>Validity</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Validity__c</fullName>
        <description>Attribute in Data Dictionary object Vehicle Relationship is &quot;VehicleRel_Validity&quot;</description>
        <label>Validity</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is&quot;VehicleRel_VehicleID&quot;</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UtilVehicleRelationship.cls
/*
    Type:       Utility for TriggerVehicleRelationship
    Purpose:    If Vehicle_Relationship__c record has change, just assign the changed value to 
                corresponding Vehicle
    User Story: US-CP-008
    Used By:    TriggerVehicleRelationship
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-03-05
*/
public class UtilVehicleRelationship {
    public static void updateVehicle(Set<Id> vehicleIds) {
        List<Vehicle__c> vehicles = [SELECT Id, Valid__c,
                                            (SELECT Id, Validity__c
                                             FROM Vehicle_Relationships__r) 
                                     FROM Vehicle__c 
                                     WHERE Id IN :vehicleIds];
        // For loop vehicles
        for (Vehicle__c vehicle : vehicles) {
            Set<String> validSet = new Set<String>();
            for (Vehicle_Relationship__c relationship : 
                    vehicle.Vehicle_Relationships__r) {
                validSet.add(relationship.Validity__c);
            }

            // Add vehicle which needs updation to list
            if (validSet.contains('Yes')) {
                vehicle.Valid__c = 'Yes';
            }
            // If all vehicle relationships is not Yes and one is unknown,
            // update vehicle to unknown
            else if (!validSet.contains('Yes') && 
                      validSet.contains('Unknown')) {
                vehicle.Valid__c = 'Unknown';
            }
            // If all vehicle relationship ares not Yes and unknown,
            // update vehicle to unknown
            else if (!validSet.contains('Yes') && 
                      validSet.contains('No')) {
                vehicle.Valid__c = 'No';
            }
        }
        
        try {
            update vehicles;
        }
        catch (DMLException e) {
            trigger.new[0].addError(e.getDMLMessage(0));
            System.debug('UtilVehicleRelationship.updateVehicle Exception: ' + e);
        }
    }
}